회원 관련 Persistence 구현
nhnacademy-be3-CookShoong/cookshoong-backend pull request #12
Opened 2023-07-04 15:02 UTC by 10kseok

회원 관리와 관련된 엔터티와 레포지토리까지만 작성하였습니다.

2023-07-04 15:11 UTC, JeongJeWan approved these changes
수고했습니다~

2023-07-04 17:51 UTC, seong1542 approved these changes

2023-07-04 22:53 UTC, unhas01 requested changes

2023-07-04 22:53 UTC, unhas01 commented on src/main/resources/application-dev.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
1

2023-07-04 22:53 UTC, unhas01 commented on src/test/java/store/cookshoong/www/cookshoongbackend/account/repository/AccountRepositoryTest.java
> +@ActiveProfiles("dev")
2

2023-07-05 00:41 UTC, 10kseok commented on src/test/java/store/cookshoong/www/cookshoongbackend/account/repository/AccountRepositoryTest.java
> +@ActiveProfiles("dev")
테스트 환경으로 이동시켰습니다!

2023-07-05 01:17 UTC, unhas01 approved these changes
수고하셨습니다.

2023-07-05 01:19 UTC, merged